### ISSUE TITLE
请问这是遇到什么问题了

### ISSUE THREAD

**Issue by Testplayers** [whjwsm/ChaoXingshixidaka#1]
Traceback (most recent call last):
  File "/ql/data/scripts/学习通实习打卡签到.py", line 56, in <module>
    clockinId = re.search(r'<input id="clockinId" type="hidden" value="(.*)">', txt, re.I).groups()[0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by WAADRI** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/学习通实习打卡签到.py", line 56, in clockinId = re.search(r'', txt, re.I).groups()[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'groups'

把你学习通账号密码私信到我邮箱WiFi86@qq.com看看

**Comment by WAADRI** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/学习通实习打卡签到.py", line 56, in clockinId = re.search(r'', txt, re.I).groups()[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'groups'

已修复
