### ISSUE TITLE
两个签到，有一个结束了，怎么选新的那个

### ISSUE THREAD

**Issue by zhiwenchen** [whjwsm/ChaoXingshixidaka#3]

**Comment by WAADRI** [comment]
你说的修猫吗，这个要问他们

**Comment by zhiwenchen** [comment]
> 你说的修猫吗，这个要问他们

不是，就是我有两个实习，一个是第一阶段的，已经结束了，但是打卡会打到这个实习上，怎么打到新的实习上

**Comment by WAADRI** [comment]
这个我不太清楚，我没有实习打卡，所以当时写这个都是用的别人的号做的测试，现在官方可能也更新了，需要的话可以发我号我看看

**Comment by zhiwenchen** [comment]
> 这个我不太清楚，我没有实习打卡，所以当时写这个都是用的别人的号做的测试，现在官方可能也更新了，需要的话可以发我号我看看

怎么发给你

**Comment by WAADRI** [comment]
加我QQ吧，2533169981

**Comment by WAADRI** [comment]
已更新
